[build]
  base = "apps/systatum"
  command = "npm install && npx tinacms build && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[email]
  provider = "postmark"
  api_key = "${POSTMARK_API_KEY}"

[dev]
  base = "apps/systatum"
  command = "npm run dev"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

