[build]
  base = "apps/systatum"
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[dev]
  base = "apps/systatum"
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"

[build.environment]
  GATSBY_PRESERVE_FILE_DOWNLOAD_CACHE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200