query postQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    category {
      ... on Category {
        name
      }
    }
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}
